### ISSUE TITLE
Problem with ref

### ISSUE THREAD

**Issue by Macklawe** [straw-hat-team/react-fullscreen#41]
```
const testRef = `React.useRef<HTMLDivElement>(null);
const` { isFullscreen, toggleFullscreen } = useFullscreen(
    testRef.current
  );
```

I have such a structure. When the component is rendered for the first time - apparently the ref null and nothing happens. When calling the component update the ref will receive the item. How can this be fixed?

**Comment by yordis** [comment]
>When the component is rendered for the first time - apparently the ref null and nothing happens.

Yes, that is how it works

So what is the issue exactly?

Does the component work when your `ref` gets attached?

**Comment by Macklawe** [comment]
Yes, but this is not what I need. In order for the ref get attached I need to do an update of the component. Then everything works

**Comment by yordis** [comment]
So what do you expect this hook to do for you then?

That seems to be your use case so I am not sure what is the issue.
